#!/bin/zsh

# Set up additional colors for exa.
EXA_COLORS="uu=0:gu=0:un=33:gn=33"
EXA_COLORS="${EXA_COLORS}:lp=34;1"
EXA_COLORS="${EXA_COLORS}:ur=33:gr=33:tr=33"
EXA_COLORS="${EXA_COLORS}:uw=31:gw=31:tw=32"
EXA_COLORS="${EXA_COLORS}:ue=32:gx=32:tx=32"
EXA_COLORS="${EXA_COLORS}:ux=32;1"

# Highlight READMEs and license files.
EXA_COLORS="${EXA_COLORS}:README=33:README.*=33"
EXA_COLORS="${EXA_COLORS}:LICENSE=33:LICENSE.*=33"
EXA_COLORS="${EXA_COLORS}:COPYING=33:COPYING.*=33"
EXA_COLORS="${EXA_COLORS}:COPYING.LESSER=33:COPYING.LESSER.*=33"

# Build definition files.
EXA_COLORS="${EXA_COLORS}:Makefile=33;1"
EXA_COLORS="${EXA_COLORS}:Cargo.toml=33;1"
EXA_COLORS="${EXA_COLORS}:SConstruct=33;1"
EXA_COLORS="${EXA_COLORS}:CMakeLists.txt=33;1"
EXA_COLORS="${EXA_COLORS}:build.gradle=33;1"
EXA_COLORS="${EXA_COLORS}:Rakefile=33;1"
EXA_COLORS="${EXA_COLORS}:Gruntfile.js=33;1"
EXA_COLORS="${EXA_COLORS}:Gruntfile.coffee=33;1"
EXA_COLORS="${EXA_COLORS}:BUILD=33;1"
EXA_COLORS="${EXA_COLORS}:BUILD.bazel=33;1"
EXA_COLORS="${EXA_COLORS}:WORKSPACE=33;1"
EXA_COLORS="${EXA_COLORS}:build.xml=33;1"
EXA_COLORS="${EXA_COLORS}:package.xml=33;1"
export EXA_COLORS
