# Inserts a blank line between shell prompts
add_newline = false

format = """
[($username(@$hostname):)](green)\
$directory\
[(\\($git_branch$git_status\\))](yellow)\
[(\\($python\\))](bright-cyan)\
$jobs\
$character\
"""

[username]
format = "[$user]($style)"
style_user = "green"
style_root = "bold red"
show_always = false

[hostname]
style = "green"
format = "[$hostname]($style)"
ssh_only = true

[directory]
truncation_length = 16
truncate_to_repo = false
truncation_symbol = "../"
format = "[$path]($style)[$read_only]($read_only_style)"
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "yellow"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "yellow"
conflicted = "x"
ahead = "+${count}"
behind = "-${count}"
diverged = "+${ahead_count}-${behind_count}"
untracked = ""
stashed = "\\$"
modified = "∗"
staged = "∗"
renamed = ""
deleted = ""

[python]
format = "[$virtualenv]($style)"
style = "bright-cyan"

[jobs]
format = "\\[[$number]($style)\\]"
number_threshold = 1
style = ""

[character]
format = " $symbol "
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[aws]
disabled = true
[azure]
disabled = true
[battery]
disabled = true
[cmake]
disabled = true
[cmd_duration]
disabled = true
[cobol]
disabled = true
[conda]
disabled = true
[crystal]
disabled = true
[custom]
disabled = true
[dart]
disabled = true
[deno]
disabled = true
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[env_var]
disabled = true
[erlang]
disabled = true
[gcloud]
disabled = true
[git_commit]
disabled = true
[git_metrics]
disabled = true
[git_state]
disabled = true
[golang]
disabled = true
[helm]
disabled = true
[hg_branch]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kotlin]
disabled = true
[kubernetes]
disabled = true
[line_break]
disabled = true
[lua]
disabled = true
[memory_usage]
disabled = true
[nim]
disabled = true
[nix_shell]
disabled = true
[nodejs]
disabled = true
[ocaml]
disabled = true
[openstack]
disabled = true
[package]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[pulumi]
disabled = true
[purescript]
disabled = true
[red]
disabled = true
[rlang]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
[scala]
disabled = true
[shell]
disabled = true
[shlvl]
disabled = true
[singularity]
disabled = true
[status]
disabled = true
[sudo]
disabled = true
[swift]
disabled = true
[terraform]
disabled = true
[time]
disabled = true
[vagrant]
disabled = true
[vcsh]
disabled = true
[vlang]
disabled = true
[zig]
disabled = true
