# Inserts a blank line between shell prompts
add_newline = false

format = """
[($username(@$hostname):)](green)\
$directory\
[(\\($git_branch$git_status\\))](yellow)\
$jobs\
$character\
"""

[directory]
truncation_length = 16
truncate_to_repo = false
truncation_symbol = "../"
format = "[$path]($style)[$read_only]($read_only_style)"
style = "blue"

[username]
format = "[$user]($style)"
style_user = "green"
style_root = "bold red"
show_always = false

[hostname]
style = "green"
format = "[$hostname]($style)"
ssh_only = true

[jobs]
format = "\\[[$number]($style)\\]"
number_threshold = 1
style = ""

[git_branch]
format = "[$branch]($style)"
style = "yellow"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "yellow"
conflicted = "x"
ahead = "+${count}"
behind = "-${count}"
diverged = "+${ahead_count}-${behind_count}"
untracked = ""
stashed = "$"
modified = "∗"
staged = "∗"
renamed = ""
deleted = ""

[character]
format = "$symbol "
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"
