# Inserts a blank line between shell prompts
add_newline = false

format = """
[($username(@$hostname):)](bold yellow)\
$directory\
[(\\($git_branch$git_status\\))](bold cyan)\
$jobs\
$character\
"""

[directory]
truncation_length = 16
truncate_to_repo = false
truncation_symbol = "../"
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold green"

[username]
format = "[$user]($style)"
style_user = "bold yellow"
style_root = "bold red"

[hostname]
style = "bold yellow"
format = "[$hostname]($style)"

[jobs]
format = "\\[[$number]($style)\\]"
number_threshold = 1

[git_branch]
format = "[$branch]($style)"
style = "bold cyan"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "bold cyan"
conflicted = "x"
ahead = "+${count}"
behind = "-${count}"
diverged = ""
untracked = ""
stashed = "$"
modified = "∗"
staged = "∗"
renamed = ""
deleted = ""

[character]
format = " $symbol "
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
